config/console.php, config/params.php, config/tests.php, resources/views/addColumnMigration.php, resources/views/createJunctionMigration.php, resources/views/createTableMigration.php, resources/views/dropColumnMigration.php, resources/views/dropTableMigration.php, resources/views/migration.php, src/Service/Generate/CreateService.php, src/Service/MigrationService.php, tests/Namespaces/CreateAddColumnCommandTest.php, tests/Namespaces/CreateCommandTest.php, tests/Namespaces/CreateDropColumnCommandTest.php, tests/Namespaces/CreateDropTableCommandTest.php, tests/Namespaces/CreateJunctionCommandTest.php, tests/Namespaces/CreateTableCommandTest.php, tests/Paths/CreateAddColumnCommandTest.php, tests/Paths/CreateCommandTest.php, tests/Paths/CreateDropColumnCommandTest.php, tests/Paths/CreateDropTableCommandTest.php, tests/Paths/CreateJunctionCommandTest.php, tests/Paths/CreateTableCommandTest.php, tests/Paths/DownCommandTest.php, tests/Paths/HistoryCommandTest.php, tests/Paths/NewCommandTest.php, tests/Paths/RedoCommandTest.php, tests/Paths/UpdateCommandTest.php
| Tests pass?   | ✔️
| Fixed issues  | https://github.com/yiisoft/yii-db-migration/issues/18
=> Enhacements

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .github/SECURITY.md, .github/dependabot.yml, .github/workflows/build.yml, .github/workflows/mutation.yml, .github/workflows/static.yml, README.md, composer.json, config/params.php, config/tests.php, infection.json.dist, phpunit.xml.dist
=> Adjust github actions.

resources/views/addColumnMigration.php, resources/views/createJunctionMigration.php, resources/views/createTableMigration.php, resources/views/dropColumnMigration.php, resources/views/dropTableMigration.php, resources/views/migration.php, src/Migration.php, src/MigrationInterface.php, src/RevertibleMigrationInterface.php, src/Service/Migrate/DownService.php, src/Service/Migrate/UpdateService.php, tests/Namespaces/CreateAddColumnCommandTest.php, tests/Namespaces/CreateCommandTest.php, tests/Namespaces/CreateDropColumnCommandTest.php, tests/Namespaces/CreateDropTableCommandTest.php, tests/Namespaces/CreateJunctionCommandTest.php, tests/Namespaces/CreateTableCommandTest.php, tests/Paths/CreateCommandTest.php
=> Fix #31: Introduce RevertibleMigrationInterface

src/Helper/ConsoleHelper.php
=> Fix baseDir package directory migration.

src/Helper/ConsoleHelper.php, src/Service/Database/ListTablesService.php
=> Fix psalm issues.

.github/workflows/build.yml, .github/workflows/mutation.yml, .github/workflows/static.yml, README.md, composer.json, config/console.php, config/params.php, tests/TestCase.php
=> Add config composer plugin

tests/MigrationTest.php, tests/TestCase.php
=> Remove output tests from console.

tests/TestCase.php
=> Clean up config last change cache.

config/params.php
=> Adopt configuration params for yiisoft/aliases

src/Service/MigrationService.php, tests/src/Command/CommandTest.php, tests/src/Command/Namespaces/CreateCommandTest.php, tests/src/Command/Paths/CreateCommandTest.php
=> For migration class name always use PascalCase-style + refactoring tests

src/Migration.php, tests/src/BaseTest.php, tests/src/MigrationTest.php
=> Fix error on create table with string column definitions

src/MigrationBuilder.php, tests/src/MigrationBuilderTest.php
=> Add methods truncateTable, renameTable, addColumn, dropColumn to MigrationBuilder

composer.json, src/MigrationBuilder.php, src/Service/MigrationService.php
=> Move prepare db to migration from MigrationBuilder to MigrationService

src/Command/CreateCommand.php
Command `yii migrate/create MyName`:
- now created class `M210124200607CreateMyName`;
- after this PR created class `M210124200607MyName`.
=> Change default migration name

README.md, src/Command/CreateCommand.php
| Fixed issues  | https://github.com/yiisoft/yii-demo/issues/112
=> Adjust console entry point in docs

README.md, config/params.php, src/Command/CreateCommand.php, src/Service/MigrationService.php, tests/src/Command/Namespaces/CreateCommandTest.php, tests/src/Command/Paths/CreateCommandTest.php
=> Rename generate/create command to migrate/create

README.md, config/console.php, tests/src/BaseTest.php
| Fixed issues  | https://github.com/yiisoft/factory/pull/78
=> Adopt factory

config/console.php, config/params.php, src/Command/CreateCommand.php, src/Command/NewCommand.php, src/Command/UpdateCommand.php, src/Service/MigrationService.php, tests/src/Command/Namespaces/NamespacesCommandTest.php, tests/src/Command/Namespaces/UpdateCommandTest.php, tests/src/Command/Paths/PathsCommandTest.php, tests/src/Command/Paths/UpdateCommandTest.php, tests/src/Service/MigrationServiceTest.php, tests/src/Service/NamespaceMigrationServiceTest.php
=> Fix config view.

config/console.php
https://github.com/yiisoft/factory/pull/86
=> Disallow definition objects in configs, except ReferenceInterface

README.md, composer.json, src/Command/DownCommand.php, src/Command/HistoryCommand.php, src/Command/NewCommand.php, src/Command/RedoCommand.php, src/Command/UpdateCommand.php, tests/src/Command/Namespaces/DownCommandTest.php, tests/src/Command/Namespaces/HistoryCommandTest.php, tests/src/Command/Namespaces/RedoCommandTest.php, tests/src/Command/Paths/DownCommandTest.php, tests/src/Command/Paths/HistoryCommandTest.php, tests/src/Command/Paths/RedoCommandTest.php
=> Fix incorrect getting value of `limit` option in commands `down`, `history` and `redo`

.editorconfig, .github/workflows/build.yml, .github/workflows/mutation.yml, composer.json, src/Service/Database/ListTablesService.php, tests/src/Command/ListTablesCommandTest.php, tests/src/Support/PostgreSqlHelper.php
=> Fix list table names in case with several schemas

config/console.php, config/params.php, src/Service/Generate/CreateService.php, src/Service/MigrationService.php, tests/src/BaseTest.php, tests/src/Command/Namespaces/CreateCommandTest.php, tests/src/ConfigTest.php, tests/src/Support/PostgreSqlHelper.php
=> Remove alias `@yiisoft/yii/db/migration`, create internal  `View` instead get from container + test

tests/src/ConfigTest.php
| Fixed issues  | https://github.com/yiisoft/di/pull/276
=> Adapt to DI changes

composer.json, tests/src/MigrationBuilderTest.php
=> Add `yiisoft/view:^5.0` support + Fix tests for PHP 8.1

README.md, composer.json
=> PR for issue-133

composer.json, resources/views/_addColumns.php, resources/views/_addComments.php, resources/views/_addForeignKeys.php, resources/views/_createTable.php, resources/views/_dropColumns.php, resources/views/_dropForeignKeys.php, resources/views/_dropTable.php, resources/views/_foreignTables.php, resources/views/addColumnMigration.php, resources/views/createTableMigration.php, resources/views/dropColumnMigration.php, resources/views/dropTableMigration.php, resources/views/migration.php, src/Service/Generate/CreateService.php, src/Service/Generate/PhpRenderer.php, tests/src/ConfigTest.php, tests/src/Support/Helper/ContainerHelper.php
| Fixed issues  | #126 
And remove dev-dependency `yiisoft/event-dispatcher`
=> Replace `yiisoft/view` with internal php renderer

src/AbstractMigrationBuilder.php, src/MigrationBuilder.php, tests/src/ConfigTest.php, tests/src/MigrationBuilderTest.php, tests/src/Support/Helper/ContainerHelper.php, tests/src/Support/Helper/PostgreSqlHelper.php, tests/src/Support/Helper/SqLiteHelper.php
=> Adapt to last changes in Yii DB

src/Service/Database/ListTablesService.php, tests/src/Support/Helper/ContainerHelper.php
=> Fix `PdoConnectionInterface` name and minor test fix

.github/workflows/build.yml, .github/workflows/mutation.yml, README.md, docker-compose.yml, tests/src/Command/ListTablesCommandTest.php, tests/src/Support/Helper/PostgreSqlHelper.php, tests/src/Support/Helper/SqLiteHelper.php
=> Synchronize with all db packages.

.github/workflows/mariadb.yml, .github/workflows/mutation.yml, .github/workflows/mysql.yml, .styleci.yml, composer.json, phpunit.xml.dist, tests/Common/AbstractMigrationBuilderTest.php, tests/Driver/Mysql/ColumnTypesTest.php, tests/Driver/Mysql/CreateCommandTest.php, tests/Driver/Mysql/CreateServiceTest.php, tests/Driver/Mysql/DownCommandTest.php, tests/Driver/Mysql/DownRunnerTest.php, tests/Driver/Mysql/HistoryCommandTest.php, tests/Driver/Mysql/ListTablesCommandTest.php, tests/Driver/Mysql/ListTablesServiceTest.php, tests/Driver/Mysql/MigrationBuilderTest.php, tests/Driver/Mysql/MigrationServiceTest.php, tests/Driver/Mysql/MigratorTest.php, tests/Driver/Mysql/NewCommandTest.php, tests/Driver/Mysql/RedoCommandTest.php, tests/Driver/Mysql/UpRunnerTest.php, tests/Driver/Mysql/UpdateCommandTest.php, tests/Support/Factory/MysqlFactory.php
=> Add `mariadb`,  `mysql` tests

src/MigrationBuilder.php, tests/Common/AbstractMigrationBuilderTest.php
=> Add methods `createView()` and `dropView()` in `MigrationBuilder::class`.

.github/workflows/build.yml, .github/workflows/composer-require-checker.yml, .github/workflows/mariadb.yml, .github/workflows/mssql.yml, .github/workflows/mutation.yml, .github/workflows/mysql.yml, .github/workflows/oracle.yml, .github/workflows/pgsql.yml, .github/workflows/sqlite.yml, .github/workflows/static.yml, src/Command/CreateCommand.php, src/Command/DownCommand.php, src/Command/HistoryCommand.php, src/Command/NewCommand.php, src/Command/RedoCommand.php, src/Command/UpdateCommand.php, tests/Common/Command/AbstractCreateCommandTest.php, tests/Common/Command/AbstractNewCommandTest.php, tests/Common/Command/AbstractUpdateCommandTest.php, tests/Driver/Mssql/CreateCommandTest.php, tests/Driver/Mssql/NewCommandTest.php, tests/Driver/Mysql/CreateCommandTest.php, tests/Driver/Mysql/NewCommandTest.php, tests/Driver/Oracle/CreateCommandTest.php, tests/Driver/Oracle/NewCommandTest.php, tests/Driver/Pgsql/CreateCommandTest.php, tests/Driver/Pgsql/NewCommandTest.php, tests/Driver/Sqlite/CreateCommandTest.php, tests/Driver/Sqlite/NewCommandTest.php
=> Raise Mutation Test 100%.

composer.json, src/Migrator.php
=> Remove `yiisoft/arrays` dependency

composer.json, src/Command/CreateCommand.php
=> Remove `yiisoft/files` dependency

src/Command/CreateCommand.php, src/Command/NewCommand.php, src/Command/UpdateCommand.php, tests/Common/Command/AbstractCreateCommandTest.php, tests/Common/Command/AbstractNewCommandTest.php, tests/Common/Command/AbstractUpdateCommandTest.php, tests/Support/Factory/MssqlFactory.php, tests/Support/Factory/MysqlFactory.php, tests/Support/Factory/OracleFactory.php, tests/Support/Factory/PostgreSqlFactory.php, tests/Support/Factory/SqLiteFactory.php, tests/Support/Helper/MigrationHelper.php
=> Support options path and namespace

src/Service/MigrationService.php, tests/Common/Command/AbstractCreateCommandTest.php
=> Show error when specified both path and namespace

src/Command/DownCommand.php, src/Command/HistoryCommand.php, src/Command/NewCommand.php, src/Command/RedoCommand.php, src/Command/UpdateCommand.php, tests/Common/Command/AbstractDownCommandTest.php, tests/Common/Command/AbstractHistoryCommandTest.php, tests/Common/Command/AbstractNewCommandTest.php, tests/Common/Command/AbstractRedoCommandTest.php, tests/Common/Command/AbstractUpdateCommandTest.php
=> Actualize option --all and --limit

src/Migrator.php, src/Service/Generate/FieldsParser.php, src/Service/Generate/ForeignKeyFactory.php, src/Service/Generate/PhpRenderer.php, src/Service/MigrationService.php
=> Refactoring 2

src/Command/CreateCommand.php, src/Service/MigrationService.php, tests/Support/Helper/MigrationHelper.php
=> More clear way to get `createNamespace`

bin/MigrationContainer.php, config/di-console.php, docs/en/usage-with-symfony-console.md
=> Update default config

src/Command/DownCommand.php, src/Command/RedoCommand.php, src/Command/UpdateCommand.php, src/Runner/DownRunner.php, src/Runner/UpdateRunner.php, src/Service/MigrationService.php, tests/Common/Command/AbstractDownCommandTest.php, tests/Common/Command/AbstractRedoCommandTest.php, tests/Common/Command/AbstractUpdateCommandTest.php
=> Improve informing

src/Command/CreateCommand.php, src/Command/NewCommand.php, src/Command/UpdateCommand.php, src/Service/MigrationService.php, tests/Common/Command/AbstractCreateCommandTest.php, tests/Common/Command/AbstractUpdateCommandTest.php, tests/Common/Service/AbstractMigrationServiceTest.php, tests/Support/Helper/MigrationHelper.php
=> Add set prefix to MigrationService setters

.github/PULL_REQUEST_TEMPLATE.md, composer.json, phpunit.xml.dist, psalm.xml
=> Improve tests

README.md, docs/en/usage-standalone.md, docs/en/usage-with-symfony.md, docs/en/usage-with-yii-console.md
=> Fix #239: Add usage with Symfony app

README.md, docs/en/testing.md, docs/en/usage-standalone.md, docs/en/usage-with-yii-console.md, src/AbstractMigrationBuilder.php, src/MigrationBuilder.php, src/Service/Generate/CreateService.php, src/Service/Generate/FieldsParser.php, src/Service/Generate/ForeignKeyFactory.php, src/Service/MigrationService.php, tests/Common/Service/AbstractMigrationServiceTest.php, tests/Support/AssertTrait.php, tests/Support/Factory/MssqlFactory.php, tests/Support/Factory/MysqlFactory.php, tests/Support/Factory/OracleFactory.php, tests/Support/Factory/PostgreSqlFactory.php, tests/Support/Factory/SqLiteFactory.php, tests/Support/Helper/ContainerHelper.php, tests/Support/Provider/ColumnTypes.php
=> Fix typos and wording

docs/en/usage-standalone.md
=> Add docs for standalone usage without configuration file

docs/guide/en/readme.md
=> Remove duplicate readme file

.github/workflows/mutation.yml, .github/workflows/static.yml, CHANGELOG.md, composer.json, psalm-8.0.xml, src/Migrator.php
=> Don't use Yii DB deprecated methods in `Migrator`

.github/workflows/mssql.yml
=> Fix MSSQL tests

tests/Common/AbstractMigrationBuilderTest.php, tests/Driver/Mysql/MigrationBuilderTest.php
- https://github.com/yiisoft/db/pull/920
=> Fix tests according changes in `db` package

CHANGELOG.md, resources/views/migration.php, tests/Common/Command/AbstractCreateCommandTest.php
=> Improve base migration template

.github/workflows/build.yml, .github/workflows/composer-require-checker.yml, .github/workflows/mssql.yml, .github/workflows/mutation.yml, .github/workflows/mysql.yml, .github/workflows/oracle.yml, .github/workflows/pgsql.yml, .github/workflows/rector.yml, .github/workflows/sqlite.yml, .github/workflows/static.yml, rector.php
=> Refactor workflows

tests/Common/AbstractMigrationBuilderTest.php, tests/Common/Command/AbstractUpdateCommandTest.php, tests/Driver/Mysql/MigrationBuilderTest.php
- https://github.com/yiisoft/db/pull/1011
| Fixed issues  |
=> Update according changes in `db` package

docs/guide/en/usage-with-yii-console.md, docs/guide/pt-BR/usage-with-yii-console.md
=> Fix `params.php` [skip ci]
