- src/Service/Database/ListTablesService.php
- src/Service/MigrationService.php
Example:
```php
./yii generate/create item --namespace App\\Module\\Rbac\\Migration
```
> Fix generate/create with options namespace.

- src/Command/UpdateCommand.php
- tests/src/Command/Namespaces/UpdateCommandTest.php
- tests/src/Command/Paths/UpdateCommandTest.php
When used in CI, it throws an error if system is up-to-date.
> Fix response code when system is up-to-date

- src/Command/DownCommand.php
- tests/src/Command/Namespaces/DownCommandTest.php
- tests/src/Command/Paths/DownCommandTest.php
> For command `migrate/down` added option `--all` and default value `1` for option `--limit`

- src/Command/CreateCommand.php
- src/Service/MigrationService.php
- tests/src/Support/Helper/ContainerHelper.php
> `MigrationService::findMigrationPath()` returns path with translated path aliases

- src/Migrator.php
- tests/Common/AbstractMigrationBuilderTest.php
- tests/Common/AbstractMigratorTest.php
- tests/Common/Command/AbstractUpdateCommandTest.php
- tests/Driver/Mssql/MigrationBuilderTest.php
- tests/Driver/Mysql/MigrationBuilderTest.php
- tests/Driver/Oracle/MigrationBuilderTest.php
- tests/Driver/Pgsql/MigrationBuilderTest.php
- tests/Support/Factory/OracleFactory.php
- tests/Support/Helper/ContainerHelper.php
- tests/Support/Helper/DbHelper.php
> Remove unnecesary `SchemaCache::class`.

- bin/MigrationContainer.php
- bin/migration
- docs/en/usage-with-symfony-console.md
> Better naming `DiConsoleSymfony.php` to `MigrationContainer.php`.

- tests/Common/AbstractMigrationBuilderTest.php
Before:
https://github.com/yiisoft/db-migration/actions/runs/6072809097/job/16473480240#step:6:16
After:
https://github.com/yiisoft/db-migration/actions/runs/6494238823/job/17636801181?pr=201#step:6:16
> Fix visability of AbstractMigrationBuilderTest::$db property in tests

- composer.json
- src/Command/CreateCommand.php
- src/MigrationBuilder.php
- src/Service/MigrationService.php
- tests/Common/AbstractMigrationBuilderTest.php
> Remove `yiisoft/strings` dependency

- resources/views/_addColumns.php
- resources/views/_createTable.php
- resources/views/_dropColumns.php
- src/Service/Generate/Column.php
- src/Service/Generate/FieldsParser.php
> Better naming for column name

- src/Command/CreateCommand.php
> Clarify options on CreateCommand

- tests/Common/AbstractMigratorTest.php
- tests/Support/Factory/MssqlFactory.php
- tests/Support/Factory/MysqlFactory.php
- tests/Support/Factory/OracleFactory.php
- tests/Support/Factory/SqLiteFactory.php
> Fix and improve tests

- src/MigrationBuilder.php
- tests/Common/AbstractMigrationBuilderTest.php
- tests/Support/Migrations/M231015155500ExecuteSql.php
> Output `rawSql()` for `execute()` method

- .github/workflows/build.yml
- bin/MigrationContainer.php
- config/di-console.php
- docs/en/usage-with-symfony-console.md
- tests/Migration/ConfigTest.php
> Fix config for added set prefixes to `MigrationService` setters

- tests/Support/Factory/OracleFactory.php
> Fix Oracle tests running locally

- src/MigrationBuilder.php
- tests/Common/Command/AbstractUpdateCommandTest.php
> Fix after update `db` package

- src/Command/RedoCommand.php
- tests/Common/Command/AbstractRedoCommandTest.php
> Support `--path` and `--namespace` options for `migrate:redo` command

- .github/workflows/rector.yml
- README.md
- src/Command/CreateCommand.php
- src/Command/DownCommand.php
- src/Command/HistoryCommand.php
- src/Command/NewCommand.php
- src/Command/RedoCommand.php
- src/Command/UpdateCommand.php
- src/Informer/ConsoleMigrationInformer.php
- src/Informer/MigrationInformerInterface.php
- src/Informer/NullMigrationInformer.php
- src/MigrationBuilder.php
- src/Migrator.php
- src/Runner/DownRunner.php
- src/Runner/UpdateRunner.php
- src/Service/Generate/CreateService.php
- src/Service/MigrationService.php
- tests/Common/Runner/AbstractDownRunnerTest.php
- tests/Common/Runner/AbstractUpRunnerTest.php
- tests/Common/Service/Database/AbstractListTablesServiceTest.php
- tests/Migration/NullMigrationInformerTest.php
- tests/Support/Stub/StubMigrationInformer.php
> Minor refactoring and cleanup

- bin/yii-db-migration
- bin/yii-db-migration.php
- config/di-console.php
- config/params.php
- docs/en/usage-with-symfony.md
- docs/en/usage-with-yii-console.md
- src/Command/CreateCommand.php
- src/Command/NewCommand.php
- src/Command/UpdateCommand.php
- src/MigrationBuilder.php
- src/Service/MigrationService.php
- tests/Common/Command/AbstractCreateCommandTest.php
- tests/Common/Command/AbstractDownCommandTest.php
- tests/Common/Command/AbstractHistoryCommandTest.php
- tests/Common/Command/AbstractNewCommandTest.php
- tests/Common/Command/AbstractRedoCommandTest.php
- tests/Common/Command/AbstractUpdateCommandTest.php
- tests/Common/Service/AbstractMigrationServiceTest.php
- tests/Support/Helper/MigrationHelper.php
> Rename config options

- CHANGELOG.md
- composer.json
- src/Service/MigrationService.php
- tests/Common/Service/AbstractMigrationServiceTest.php
Fix when there is a path to the namespace but the directory does not exist.
> There is a namespace but the directory does not exist

- .github/workflows/build.yml
- .github/workflows/mssql.yml
- .github/workflows/mutation.yml
- .github/workflows/mysql.yml
- .github/workflows/oracle.yml
- .github/workflows/pgsql.yml
- .github/workflows/sqlite.yml
- .github/workflows/static.yml
- CHANGELOG.md
- UPGRADE.md
- src/AbstractMigrationBuilder.php
- src/MigrationBuilder.php
- src/Migrator.php
- tests/Common/AbstractMigrationBuilderTest.php
- tests/Common/AbstractMigratorTest.php
- tests/Driver/Mssql/MigrationBuilderTest.php
- tests/Driver/Mysql/MigrationBuilderTest.php
- tests/Driver/Oracle/MigrationBuilderTest.php
- tests/Driver/Pgsql/MigrationBuilderTest.php
- tests/Support/Factory/MssqlFactory.php
- https://github.com/yiisoft/db/pull/905
| Fixed issues  |
> Use new column builder

- CHANGELOG.md
- src/AbstractMigrationBuilder.php
- src/MigrationBuilder.php
- https://github.com/yiisoft/db/pull/917
> Rename `ColumnSchemaInterface` to `ColumnInterface`

- CHANGELOG.md
- src/AbstractMigrationBuilder.php
- tests/Common/AbstractMigrationBuilderTest.php
- tests/Driver/Sqlite/MigrationBuilderTest.php
> Explicitly mark nullable parameters

- CHANGELOG.md
- README.md
- composer.json
> Remove `ext-filter` from require section of `composer.json`

- CHANGELOG.md
- src/Migrator.php
- tests/Common/AbstractMigratorTest.php
- tests/Support/Migrations/M250312122400ChangeDbPrefixUp.php
- tests/Support/Migrations/M250312122500ChangeDbPrefixDown.php
> Revert transactional migration when adding migration to history fails

- CHANGELOG.md
- src/MigrationBuilder.php
- src/Service/Generate/ForeignKeyFactory.php
- tests/Common/AbstractMigrationBuilderTest.php
- tests/Driver/Mysql/MigrationBuilderTest.php
- https://github.com/yiisoft/db/pull/981
> Update according changes to `db` package
